<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class  CommentaireRepository extends EntityRepository
{
	public function FindAllComment($listListe)
  {
    // Méthode 1 : en passant par l'EntityManager

    $qb = $this->createQueryBuilder('a');
    $qb
    ->where('a.ObjetListe = :id')
    ->setParameter('id', $listListe)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
  }
}
