<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ObjetListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JointureFamilleRepository extends EntityRepository
{
	public function FamilleUserFindAll()
	{
		// Méthode 1 : en passant par l'EntityManager
    $qb = $this->createQueryBuilder('a');
  	$qb
    ->leftJoin('a.famille', 'b')
  ;



  return $qb
    ->getQuery()
    ->getResult()
  ;
	}





}
