<?php

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;

/**
 * ObjetListeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjetListeRepository extends EntityRepository
{
	public function myFindAll($iduser)
	{
		// Méthode 1 : en passant par l'EntityManager
    $qb = $this->createQueryBuilder('a');
  	$qb
    ->where('a.User = :id')
    ->setParameter('id', $iduser)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
	}


  public function FindAllOther($user)
  {
    // Méthode 1 : en passant par l'EntityManager

    $qb = $this->createQueryBuilder('a');
    $qb
    ->where('a.User = :id')
    ->setParameter('id', $user)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
  }

    public function FamilleUserFindAll()
  {
    // Méthode 1 : en passant par l'EntityManager
    $qb = $this->createQueryBuilder('a');
    $qb
    ->leftJoin('a.famille', 'b')
  ;



  return $qb
    ->getQuery()
    ->getResult()
  ;
  }
}
