<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function FindUserFromId($iduser)
  {
    // Méthode 1 : en passant par l'EntityManager

    $qb = $this->createQueryBuilder('a');
    $qb
    ->where('a.id = :id')
    ->setParameter('id', $iduser)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
  }

 
}
