<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function FindUserFromId($iduser)
  {
    // Méthode 1 : en passant par l'EntityManager

    $qb = $this->createQueryBuilder('a');
    $qb
    ->where('a.id = :id')
    ->setParameter('id', $iduser)
  ;

  return $qb
    ->getQuery()
    ->getResult()
  ;
  }


	public function FindFamille($idfamille)
	{

		$qb1 = $this->createQueryBuilder('a');
		$qb1
		->leftJoin('a.famille', 'b')
		->where('b = :id')
		->setParameter('id', $idfamille)
		;
		return $qb1
			->getQuery()
			->getResult();


}}
